apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portafolio-ingress
  namespace: web
spec:
  rules:
  - host: localhost
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: portafolio-svc
            port:
              number: 80
