name: Build image | Docker hub

run-name: ${{ github.actor }} Build and push image to Docker Hub 🚀

on:
  push:
    branches:
      - testing
      - main

env:
  TAG: ''

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Set tag name for build image
        run: |
          if [ ${{ github.ref_name }} == 'main' ]; then
            echo "TAG=latest" >> $GITHUB_ENV
          else
            echo "TAG=testing" >> $GITHUB_ENV
          fi
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{github.repository}}:${{env.TAG}}
      - name: Restart service on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            kubectl get namespaces

# docker pull ${{github.repository}}:${{env.TAG}}
# docker run -d -p 80:80 ${{github.repository}}:${{env.TAG}}
