name: Build image | Docker hub

run-name: ${{ github.actor }} Build and push image to Docker Hub 🚀

on:
  push:
    branches:
      - testing
      - main
    paths-ignore:
      - '*.md' # Ignore changes to readme files in the repository root
      - '**/*.md' # Ignore changes to readme files in any subdirectory
      - '.github/**' # Ignore changes to files in the .github directory

env:
  TAG: ''

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Set tag name for build image
        run: |
          if [ ${{ github.ref_name }} == 'main' ]; then
            echo "TAG=latest" >> $GITHUB_ENV
          else
            echo "TAG=testing" >> $GITHUB_ENV
          fi
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{github.repository}}:${{env.TAG}}

  restart-service-testing:
    if: ${{ github.ref_name == 'testing'}}
    name: restart-service-testing
    runs-on: ubuntu-latest
    needs: build-image
    steps:
      - name: Restart service
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            microk8s kubectl rollout restart deployment portafolio -n web-testing;

  restart-service-production:
    if: ${{ github.ref_name == 'main'}}
    name: restart-service-production
    runs-on: ubuntu-latest
    needs: build-image
    steps:
      - name: Restart service
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            microk8s kubectl rollout restart deployment portafolio -n web;
